env:
  browser: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - react
rules: 
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  "@typescript-eslint/triple-slash-reference": off
ignorePatterns:
  - "vite.config.*"
