/* tslint:disable */
/* eslint-disable */
/**
 * Open API Document
 * description
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: ym.u.ichiro@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUser200ResponseData
 */
export interface GetUser200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetUser200ResponseData
     */
    status: GetUser200ResponseDataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof GetUser200ResponseData
     */
    message: string;
}


/**
 * @export
 */
export const GetUser200ResponseDataStatusEnum = {
    Ok: 'ok',
    Error: 'error'
} as const;
export type GetUser200ResponseDataStatusEnum = typeof GetUser200ResponseDataStatusEnum[keyof typeof GetUser200ResponseDataStatusEnum];


/**
 * Check if a given object implements the GetUser200ResponseData interface.
 */
export function instanceOfGetUser200ResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function GetUser200ResponseDataFromJSON(json: any): GetUser200ResponseData {
    return GetUser200ResponseDataFromJSONTyped(json, false);
}

export function GetUser200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUser200ResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': json['message'],
    };
}

export function GetUser200ResponseDataToJSON(value?: GetUser200ResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
    };
}

