version: "3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    platform: linux/amd64
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ../packages/open-api/specfile.yml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
