version: "3"
services:
  # ----------------
  # MYSQL Container
  # ----------------
  database:
    image: mysql:8.0
    platform: linux/amd64
    container_name: database
    env_file:
      - ../../.env
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    ports:
      - "3306:3306"
    command: mysqld --innodb_use_native_aio=0
    volumes:
      - ../cnf:/etc/mysql/conf.d/:ro
      - ../logs:/var/log/mysql:rw
      - ../sql/init.development.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql:/var/lib/mysql
    networks:
      - primary

networks:
  primary:
    driver: bridge

volumes:
  mysql:
